[package]
name = "surveilr"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.7", features = ["derive"] }
hostname = "0.3.1"
lazy_static = "1.4.0"
regex = { version = "1.10.2", features = ["std"], default-features = false }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
sha1 = "0.10.6"
sqlx = { version = "0.7.2", features = ["runtime-tokio-native-tls", "sqlite"]}
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread" ]}
walkdir = "2.4.0"
