[package]
name = "surveilr"
version = "0.3.1"
edition = "2021"

# Before getting arbitrary crates check https://blessed.rs for opinionated list of "best" crates.
[dependencies]
anyhow = "1.0.75"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.7", features = ["derive"] }
clap-markdown = "0.1.3"
hostname = "0.3.1"
indoc = "2.0.4"
lazy_static = "1.4.0"
regex = { version = "1.10.2", features = ["std"], default-features = false }
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.27"
sha1 = "0.10.6"
toml = "0.8.8"
walkdir = "2.4.0"
ulid = { version = "1.1.0", features = ["rand", "std", "serde", "uuid"] }
