//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "code_notebook_cell")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code_notebook_cell_id: String,
    pub notebook_kernel_id: String,
    pub notebook_name: String,
    pub cell_name: String,
    pub cell_governance: Option<String>,
    pub interpretable_code: String,
    pub interpretable_code_hash: String,
    pub description: Option<String>,
    pub arguments: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub created_by: Option<String>,
    pub updated_at: Option<DateTimeUtc>,
    pub updated_by: Option<String>,
    pub deleted_at: Option<DateTimeUtc>,
    pub deleted_by: Option<String>,
    pub activity_log: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::code_notebook_kernel::Entity",
        from = "Column::NotebookKernelId",
        to = "super::code_notebook_kernel::Column::CodeNotebookKernelId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    CodeNotebookKernel,
    #[sea_orm(has_many = "super::code_notebook_state::Entity")]
    CodeNotebookState,
}

impl Related<super::code_notebook_kernel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CodeNotebookKernel.def()
    }
}

impl Related<super::code_notebook_state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CodeNotebookState.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
